### ISSUE TITLE
Generate classifier training inputs for production

### ISSUE THREAD

**Issue by danielsf** [AllenInstitute/DeepCell#34]
Once we have completed #31 and collected all of the labeled data, run the code from #31 to generate the inputs that will be used for training the classifier.

**Tasks**
- [ ] Run train/test split code on May 2022 labeled data to produce the initial test/train split
- [ ] Save results somewhere on disk that they will be preserved (so that, among other things, we can make sure that future test sets are a superset of this one)

**Comment by aamster** [comment]
Data is at `/allen/aibs/informatics/aamster/ssf/classifier`
